export const NGROK_ADDRESS = "https://a27f-35-237-124-108.ngrok.io";

export const LANGUAGE_ICONS = {
  JavaScript: "grommet-icons:js",
  TypeScript: "logos:typescript-icon",
  Python: "logos:python",
  UNK: "noto:disguised-face",
  Go: "logos:go",
  "C++": "logos:c-plusplus",
  Rust: "logos:rust",
  Java: "logos:java",
  C: "logos:c",
  Shell: "vscode-icons:file-type-powershell",
  Ruby: "logos:ruby",
  HTML: "logos:html-5",
  Vue: "logos:vue",
  "C#": "logos:c-sharp",
  PHP: "logos:php",
  Swift: "logos:swift",
  CSS: "logos:css-3",
  "Jupyter Notebook": "logos:jupyter",
  "Vim script": "logos:vim",
  Dart: "logos:dart",
  Haskell: "logos:haskell-icon",
  PowerShell: "vscode-icons:file-type-powershell",
  Elixir: "vscode-icons:file-type-elixir",
  Lua: "logos:lua",
  SCSS: "vscode-icons:file-type-scss2",
  "Emacs Lisp": "vscode-icons:file-type-emacs",
  Clojure: "logos:clojure",
  Batchfile: "logos:batch",
  Scala: "logos:scala",
  Nix: "vscode-icons:file-type-nix",
  Crystal: "logos:crystal",
  Kotlin: "logos:kotlin",
  CMake: "vscode-icons:file-type-cmake",
  Groovy: "vscode-icons:file-type-groovy",
  Markdown: "logos:md",
  OCaml: "vscode-icons:file-type-ocaml",
  Nunjucks: "vscode-icons:file-type-nunjucks",
  "Objective-C": "vscode-icons:file-type-objectivec",
  Blade: "vscode-icons:file-type-blade",
  V: "file-icons:v",
  Nim: "vscode-icons:file-type-nim",
  Dockerfile: "logos:docker-icon",
  Roff: "akar-icons:file",
  Assembly: "vscode-icons:file-type-assembly",
  Julia: "vscode-icons:file-type-julia",
  Zig: "vscode-icons:file-type-zig",
  WebAssembly: "logos:webassembly",
  FreeMarker: "vscode-icons:file-type-freemarker",
  Makefile: "vscode-icons:file-type-makefile",
};

export const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];
